Repository Darshan-AS/dopagent_scraper, pull requests merged in 2020-12, with the labels that each got.

#16 Improvement/project management and dependencies
  .devcontainer/devcontainer.json
  .gitignore
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  docker-compose.yml
  poetry.lock
  pyproject.toml
  scraper/constants.py
  scraper/items/__init__.py
  scraper/loaders/__init__.py
  scraper/loaders/account_loader.py
  scraper/loaders/auth_token_loader.py
  scraper/loaders/report_loader.py
  scraper/middlewares.py
  scraper/pipelines/__init__.py
  scraper/pipelines/account_pipeline.py
  scraper/pipelines/report_pipeline.py
  scraper/settings.py
  scraper/spiders/__init__.py
  scraper/spiders/accounts/__init__.py
  scraper/spiders/accounts/accounts_spider.py
  scraper/spiders/accounts/utils.py
  scraper/spiders/auth/__init__.py
  scraper/spiders/auth/auth_spider.py
  scraper/spiders/auth/selectors.py
  scraper/spiders/installments/__init__.py
  scraper/spiders/installments/installments_spider.py
  scraper/spiders/reports/__init__.py
  scraper/spiders/reports/reports_spider.py
  scraper/spiders/reports/utils.py
  scraper/utils.py
  setup.cfg
Labels: improvement

#18 Fix pipeline cold start error
  Makefile
  scraper/items/auth_token_item.py
  scraper/pipelines/account_pipeline.py
  scraper/pipelines/report_pipeline.py
  scraper/spiders/auth/utils.py
Labels: bug

#19 Reformat files and fix build-tools
  Makefile
  pyproject.toml
  scraper/constants.py
  scraper/loaders/account_loader.py
  scraper/loaders/report_loader.py
  scraper/loaders/transaction_loader.py
  scraper/middlewares.py
  scraper/pipelines/account_pipeline.py
  scraper/pipelines/report_pipeline.py
  scraper/settings.py
  scraper/spiders/auth/auth_spider.py
  scraper/spiders/auth/utils.py
  scraper/spiders/installments/installments_spider.py
  scraper/spiders/installments/selectors.py
  scraper/spiders/installments/utils.py
  scraper/spiders/selectors.py
  scraper/spiders/utils.py
  scraper/utils.py
Labels: improvement

#20 Fix backslash error in Makefile
  Makefile
Labels: bug

#21 Fix socket issue in container
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  Dockerfile
  Makefile
Labels: bug

#25 Add agent_id in authtoken
  scraper/items/auth_token_item.py
  scraper/spiders/auth/auth_spider.py
  scraper/spiders/auth/utils.py
Labels: feature

#26 Fix agent_id wrongly formatted in auth_token
  scraper/loaders/auth_token_loader.py
Labels: bug

#27 Improve docker builds
  .dockerignore
  Dockerfile
  docker-compose.yml
Labels: improvement

#28 Improve docker builds
  Dockerfile
Labels: improvement
